# runs the engine on port 3000
version: "3.9"
services:
  engine:
    image: ghcr.io/v3xlabs/v3x-property-engine:latest
    ports:
      - "3000:3000"
  # Database
  postgres:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
