/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SessionsImport } from './routes/sessions'
import { Route as DebugImport } from './routes/debug'
import { Route as CreateImport } from './routes/create'
import { Route as AboutImport } from './routes/about'
import { Route as ItemIdImport } from './routes/$itemId'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as SearchIndexImport } from './routes/search/index'
import { Route as ProductsIndexImport } from './routes/products/index'
import { Route as LogsIndexImport } from './routes/logs/index'
import { Route as ItemsIndexImport } from './routes/items/index'
import { Route as UserUserIdImport } from './routes/user/$userId'
import { Route as ItemItemIdIndexImport } from './routes/item/$itemId/index'
import { Route as ItemItemIdEditImport } from './routes/item/$itemId/edit'

// Create/Update Routes

const SessionsRoute = SessionsImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRoute,
} as any)

const DebugRoute = DebugImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRoute,
} as any)

const CreateRoute = CreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const ItemIdRoute = ItemIdImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const SearchIndexRoute = SearchIndexImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIndexRoute = ProductsIndexImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any)

const LogsIndexRoute = LogsIndexImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRoute,
} as any)

const ItemsIndexRoute = ItemsIndexImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRoute,
} as any)

const UserUserIdRoute = UserUserIdImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRoute,
} as any)

const ItemItemIdIndexRoute = ItemItemIdIndexImport.update({
  id: '/item/$itemId/',
  path: '/item/$itemId/',
  getParentRoute: () => rootRoute,
} as any)

const ItemItemIdEditRoute = ItemItemIdEditImport.update({
  id: '/item/$itemId/edit',
  path: '/item/$itemId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$itemId': {
      id: '/$itemId'
      path: '/$itemId'
      fullPath: '/$itemId'
      preLoaderRoute: typeof ItemIdImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateImport
      parentRoute: typeof rootRoute
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugImport
      parentRoute: typeof rootRoute
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsImport
      parentRoute: typeof rootRoute
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdImport
      parentRoute: typeof rootRoute
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsIndexImport
      parentRoute: typeof rootRoute
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/item/$itemId/edit': {
      id: '/item/$itemId/edit'
      path: '/item/$itemId/edit'
      fullPath: '/item/$itemId/edit'
      preLoaderRoute: typeof ItemItemIdEditImport
      parentRoute: typeof rootRoute
    }
    '/item/$itemId/': {
      id: '/item/$itemId/'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof ItemItemIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$itemId': typeof ItemIdRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/debug': typeof DebugRoute
  '/sessions': typeof SessionsRoute
  '/user/$userId': typeof UserUserIdRoute
  '/items': typeof ItemsIndexRoute
  '/logs': typeof LogsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/search': typeof SearchIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/item/$itemId/edit': typeof ItemItemIdEditRoute
  '/item/$itemId': typeof ItemItemIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$itemId': typeof ItemIdRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/debug': typeof DebugRoute
  '/sessions': typeof SessionsRoute
  '/user/$userId': typeof UserUserIdRoute
  '/items': typeof ItemsIndexRoute
  '/logs': typeof LogsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/search': typeof SearchIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/item/$itemId/edit': typeof ItemItemIdEditRoute
  '/item/$itemId': typeof ItemItemIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$itemId': typeof ItemIdRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/debug': typeof DebugRoute
  '/sessions': typeof SessionsRoute
  '/user/$userId': typeof UserUserIdRoute
  '/items/': typeof ItemsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/item/$itemId/edit': typeof ItemItemIdEditRoute
  '/item/$itemId/': typeof ItemItemIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$itemId'
    | '/about'
    | '/create'
    | '/debug'
    | '/sessions'
    | '/user/$userId'
    | '/items'
    | '/logs'
    | '/products'
    | '/search'
    | '/settings'
    | '/item/$itemId/edit'
    | '/item/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$itemId'
    | '/about'
    | '/create'
    | '/debug'
    | '/sessions'
    | '/user/$userId'
    | '/items'
    | '/logs'
    | '/products'
    | '/search'
    | '/settings'
    | '/item/$itemId/edit'
    | '/item/$itemId'
  id:
    | '__root__'
    | '/'
    | '/$itemId'
    | '/about'
    | '/create'
    | '/debug'
    | '/sessions'
    | '/user/$userId'
    | '/items/'
    | '/logs/'
    | '/products/'
    | '/search/'
    | '/settings/'
    | '/item/$itemId/edit'
    | '/item/$itemId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemIdRoute: typeof ItemIdRoute
  AboutRoute: typeof AboutRoute
  CreateRoute: typeof CreateRoute
  DebugRoute: typeof DebugRoute
  SessionsRoute: typeof SessionsRoute
  UserUserIdRoute: typeof UserUserIdRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ItemItemIdEditRoute: typeof ItemItemIdEditRoute
  ItemItemIdIndexRoute: typeof ItemItemIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemIdRoute: ItemIdRoute,
  AboutRoute: AboutRoute,
  CreateRoute: CreateRoute,
  DebugRoute: DebugRoute,
  SessionsRoute: SessionsRoute,
  UserUserIdRoute: UserUserIdRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ItemItemIdEditRoute: ItemItemIdEditRoute,
  ItemItemIdIndexRoute: ItemItemIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$itemId",
        "/about",
        "/create",
        "/debug",
        "/sessions",
        "/user/$userId",
        "/items/",
        "/logs/",
        "/products/",
        "/search/",
        "/settings/",
        "/item/$itemId/edit",
        "/item/$itemId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$itemId": {
      "filePath": "$itemId.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/create": {
      "filePath": "create.tsx"
    },
    "/debug": {
      "filePath": "debug.tsx"
    },
    "/sessions": {
      "filePath": "sessions.tsx"
    },
    "/user/$userId": {
      "filePath": "user/$userId.tsx"
    },
    "/items/": {
      "filePath": "items/index.tsx"
    },
    "/logs/": {
      "filePath": "logs/index.tsx"
    },
    "/products/": {
      "filePath": "products/index.tsx"
    },
    "/search/": {
      "filePath": "search/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    },
    "/item/$itemId/edit": {
      "filePath": "item/$itemId/edit.tsx"
    },
    "/item/$itemId/": {
      "filePath": "item/$itemId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
