name: 🚚 Deploy Web

on:
  push:
    branches:
      - master

env:
  NODE_OPTIONS: "--max_old_space_size=8192"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Build
        working-directory: ./web
        run: NODE_ENV=production pnpm run build

      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@v0.1.2-pre.4
        with:
          app_id: "289666393082386978"
          server: https://api.edgeserver.io
          token: ${{ secrets.SIGNAL_TOKEN }}
          directory: web/dist
